name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: |
          sudo apt-get update && sudo apt-get install openssh-client -y

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to EC2
        run: |
          scp -r ./dist ubuntu@${{ secrets.EC2_HOST }}:~/internshiptask1

      - name: SSH into EC2 and setup environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/internshiptask1
            pm2 delete nestjs-app || true
            pm2 start dist/main.js --name "nestjs-app"
            pm2 save
            sudo nginx -t
            sudo systemctl restart nginx

      - name: Complete Deployment
        run: echo "Deployment completed successfully!"
