name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update system and install prerequisites
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y build-essential
        sudo apt-get install -y nginx

    - name: Clone repository
      run: git clone https://github.com/VinodPandhare/internshiptask1

    - name: Install NVM and Node.js LTS
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install --lts

    - name: Use Node.js LTS
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm use --lts

    - name: Install project dependencies and build
      run: |
        cd internshiptask1  # Adjust if needed based on clone location
        npm install
        npm run build

    - name: Configure NGINX
      run: |
        sudo tee /etc/nginx/sites-available/demo > /dev/null <<EOF
        server {
            listen 80;
            server_name YOUR_PUBLIC_IP_OR_DOMAIN;

            location / {
                proxy_pass http://127.0.0.1:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
            }
        }
        EOF
        sudo ln -s /etc/nginx/sites-available/demo /etc/nginx/sites-enabled/
        sudo nginx -t
        sudo systemctl restart nginx
        sudo ufw allow 'Nginx Full'
        sudo ufw enable

    - name: Start application with PM2
      run: |
        npm install -g pm2
        pm2 start dist/main.js --name "nestjs-app"
        pm2 save
        pm2 startup

    - name: Cleanup
      run: |
        cd ~  # Return to home directory
        rm -rf internshiptask1  # Remove cloned repository

    - name: Final check
      run: |
        echo "Deployment completed successfully."

